python Jason_Teng_PA4.py -alg q -alpha 0.0 -plotname q_alpha_0.0
python Jason_Teng_PA4.py -alg q -alpha 0.01 -plotname q_alpha_0.01
python Jason_Teng_PA4.py -alg q -alpha 0.05 -plotname q_alpha_0.05
python Jason_Teng_PA4.py -alg q -alpha 0.1 -plotname q_alpha_0.1
python Jason_Teng_PA4.py -alg q -alpha 0.5 -plotname q_alpha_0.5
python Jason_Teng_PA4.py -alg q -alpha 1.0 -plotname q_alpha_1.0
python Jason_Teng_PA4.py -alg q -epsilon 0.0 -plotname q_epsilon_0.0
python Jason_Teng_PA4.py -alg q -epsilon 0.1 -plotname q_epsilon_0.1
python Jason_Teng_PA4.py -alg q -epsilon 0.25 -plotname q_epsilon_0.25
python Jason_Teng_PA4.py -alg q -epsilon 0.5 -plotname q_epsilon_0.5
python Jason_Teng_PA4.py -alg q -epsilon 1.0 -plotname q_epsilon_1.0

python Jason_Teng_PA4.py -alg s -alpha 0.0 -plotname s_alpha_0.0
python Jason_Teng_PA4.py -alg s -alpha 0.01 -plotname s_alpha_0.01
python Jason_Teng_PA4.py -alg s -alpha 0.05 -plotname s_alpha_0.05
python Jason_Teng_PA4.py -alg s -alpha 0.1 -plotname s_alpha_0.1
python Jason_Teng_PA4.py -alg s -alpha 0.5 -plotname s_alpha_0.5
python Jason_Teng_PA4.py -alg s -alpha 1.0 -plotname s_alpha_1.0
python Jason_Teng_PA4.py -alg s -epsilon 0.0 -plotname s_epsilon_0.0
python Jason_Teng_PA4.py -alg s -epsilon 0.1 -plotname s_epsilon_0.1
python Jason_Teng_PA4.py -alg s -epsilon 0.25 -plotname s_epsilon_0.25
python Jason_Teng_PA4.py -alg s -epsilon 0.5 -plotname s_epsilon_0.5
python Jason_Teng_PA4.py -alg s -epsilon 1.0 -plotname s_epsilon_1.0
python Jason_Teng_PA4.py -alg s -lambda 0.0 -plotname s_lambda_0.0
python Jason_Teng_PA4.py -alg s -lambda 0.25 -plotname s_lambda_0.25
python Jason_Teng_PA4.py -alg s -lambda 0.5 -plotname s_lambda_0.5
python Jason_Teng_PA4.py -alg s -lambda 0.75 -plotname s_lambda_0.75
python Jason_Teng_PA4.py -alg s -lambda 1.0 -plotname s_lambda_1.0
